// Package cluster drives ACM Agent-based managed cluster create on provider VMs.
package cluster

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/dasmlab/mini-mock/internal/config"
	"github.com/dasmlab/mini-mock/internal/netcfg"
	"github.com/dasmlab/mini-mock/internal/provider"
)

// Options control create/destroy.
type Options struct {
	DryRun   bool
	Manual   bool
	SkipWait bool
	WorkDir  string
}

// Create provisions network services, 3 VMs, and ACM CR templates.
func Create(ctx context.Context, cfg *config.ClusterConfig, p provider.Provider, opts Options) error {
	if config.IsLabProfile(cfg.Cluster.Profile) {
		fmt.Fprintln(os.Stderr, "warning: lab-small profile is unsupported — Assisted Installer may reject hosts or operators may degrade")
	}

	work := opts.WorkDir
	if work == "" {
		work = filepath.Join("data", "cluster-"+cfg.Cluster.Name)
	}
	if err := os.MkdirAll(work, 0o755); err != nil {
		return err
	}

	net := provider.NetworkSpec{
		Name:      cfg.Provider.Network,
		CIDR:      cfg.Network.MachineCIDR,
		Gateway:   cfg.Network.Gateway,
		DHCPStart: or(cfg.Network.DHCPStart, "192.168.130.100"),
		DHCPEnd:   or(cfg.Network.DHCPEnd, "192.168.130.150"),
		Forward:   "nat",
	}
	if err := p.EnsureNetwork(ctx, net); err != nil {
		return err
	}

	if err := netcfg.WriteHAProxy(work, cfg); err != nil {
		return err
	}
	if err := netcfg.WriteDNSMasq(work, cfg); err != nil {
		return err
	}
	if err := writeACMCRs(work, cfg); err != nil {
		return err
	}

	nodes, err := expandNodes(cfg)
	if err != nil {
		return err
	}
	for _, n := range nodes {
		if err := p.CreateNode(ctx, n); err != nil {
			return fmt.Errorf("create %s: %w", n.Name, err)
		}
	}

	printManualClusterNext(cfg, work, nodes, opts)
	return nil
}

// Status summarizes expected resources.
func Status(cfg *config.ClusterConfig) error {
	fmt.Printf("cluster: %s.%s\n", cfg.Cluster.Name, cfg.Cluster.BaseDomain)
	fmt.Printf("profile: %s provider: %s\n", cfg.Cluster.Profile, cfg.Provider.Type)
	fmt.Printf("apiVIP: %s ingressVIP: %s\n", cfg.Network.APIVIP, cfg.Network.IngressVIP)
	nodes, err := expandNodes(cfg)
	if err != nil {
		return err
	}
	for _, n := range nodes {
		fmt.Printf("  node %s mac=%s ip=%s cpu=%d memMiB=%d diskGiB=%d\n",
			n.Name, n.MAC, n.IP, n.CPU, n.MemoryMiB, n.DiskGiB)
	}
	fmt.Println()
	fmt.Println("On hub: oc get agents -A ; oc get agentclusterinstall,clusterdeployment -A")
	return nil
}

// Destroy removes VMs for the cluster.
func Destroy(ctx context.Context, cfg *config.ClusterConfig, p provider.Provider) error {
	nodes, err := expandNodes(cfg)
	if err != nil {
		return err
	}
	for _, n := range nodes {
		_ = p.StopNode(ctx, n.Name)
		if err := p.DeleteNode(ctx, n.Name); err != nil {
			fmt.Fprintf(os.Stderr, "warning: delete %s: %v\n", n.Name, err)
		}
	}
	fmt.Println("Also delete ACM CRs on the hub (ClusterDeployment, AgentClusterInstall, InfraEnv) when ready.")
	return nil
}

// AttachAndBoot attaches a discovery ISO to all nodes and powers them on.
func AttachAndBoot(ctx context.Context, cfg *config.ClusterConfig, p provider.Provider, iso string) error {
	nodes, err := expandNodes(cfg)
	if err != nil {
		return err
	}
	for _, n := range nodes {
		if err := p.AttachISO(ctx, n.Name, iso); err != nil {
			fmt.Fprintf(os.Stderr, "warning: attach iso %s: %v\n", n.Name, err)
		}
		if err := p.StartNode(ctx, n.Name); err != nil {
			return err
		}
	}
	return nil
}

func expandNodes(cfg *config.ClusterConfig) ([]provider.NodeSpec, error) {
	baseIP := net.ParseIP(cfg.Nodes.IPBase)
	if baseIP == nil {
		return nil, fmt.Errorf("invalid nodes.ipBase %q", cfg.Nodes.IPBase)
	}
	base := baseIP.To4()
	if base == nil {
		return nil, fmt.Errorf("nodes.ipBase must be IPv4")
	}
	prefix := cfg.Nodes.MACPrefix
	out := make([]provider.NodeSpec, 0, cfg.Nodes.Count)
	for i := 0; i < cfg.Nodes.Count; i++ {
		ip := make(net.IP, 4)
		copy(ip, base)
		ip[3] = base[3] + byte(i)
		mac := fmt.Sprintf("%s:%02x", prefix, 0x21+i)
		name := fmt.Sprintf("%s-master-%d", cfg.Cluster.Name, i)
		out = append(out, provider.NodeSpec{
			Name:      name,
			CPU:       cfg.Nodes.CPU,
			MemoryMiB: cfg.Nodes.MemoryMiB,
			DiskGiB:   cfg.Nodes.DiskGiB,
			MAC:       mac,
			IP:        ip.String(),
			Network:   cfg.Provider.Network,
			Pool:      cfg.Provider.StoragePool,
		})
	}
	return out, nil
}

func writeACMCRs(dir string, cfg *config.ClusterConfig) error {
	path := filepath.Join(dir, "acm-resources.yaml")
	const tpl = `# Generated by mini-mock — apply on the ACM hub after pull-secret Secret exists.
# oc create namespace {{.Name}}
# oc create secret generic pull-secret -n {{.Name}} --from-file=.dockerconfigjson=$PULL_SECRET_FILE --type=kubernetes.io/dockerconfigjson
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{.Name}}
  namespace: {{.Name}}
spec:
  baseDomain: {{.BaseDomain}}
  clusterName: {{.Name}}
  platform:
    agentBareMetal:
      agentSelector: {}
  pullSecretRef:
    name: pull-secret
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{.Name}}
    version: v1beta1
---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{.Name}}
  namespace: {{.Name}}
spec:
  clusterDeploymentRef:
    name: {{.Name}}
  imageSetRef:
    name: img{{.VersionCompact}}-x86-64-appsub
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
    machineNetwork:
    - cidr: {{.MachineCIDR}}
  provisionRequirements:
    controlPlaneAgents: 3
  sshPublicKey: "{{.SSHPlaceholder}}"
  apiVIP: {{.APIVIP}}
  ingressVIP: {{.IngressVIP}}
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: {{.Name}}
  namespace: {{.Name}}
spec:
  clusterRef:
    name: {{.Name}}
    namespace: {{.Name}}
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: "{{.SSHPlaceholder}}"
  nmStateConfigLabelSelector:
    matchLabels:
      mini-mock.dasmlab.org/cluster: {{.Name}}
`
	t, err := template.New("acm").Parse(tpl)
	if err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	ver := strings.ReplaceAll(cfg.Cluster.Version, ".", "")
	return t.Execute(f, map[string]string{
		"Name":           cfg.Cluster.Name,
		"BaseDomain":     cfg.Cluster.BaseDomain,
		"Version":        cfg.Cluster.Version,
		"VersionCompact": ver,
		"MachineCIDR":    cfg.Network.MachineCIDR,
		"APIVIP":         cfg.Network.APIVIP,
		"IngressVIP":     cfg.Network.IngressVIP,
		"SSHPlaceholder": "${SSH_PUBLIC_KEY}",
	})
}

func printManualClusterNext(cfg *config.ClusterConfig, work string, nodes []provider.NodeSpec, opts Options) {
	fmt.Println()
	fmt.Println("=== cluster create: next steps ===")
	fmt.Printf("Generated under %s:\n", work)
	fmt.Println("  - haproxy.cfg / dnsmasq fragments")
	fmt.Println("  - acm-resources.yaml")
	fmt.Println("1. Apply DNS + HAProxy on the provisioning host (see net templates)")
	fmt.Println("2. On hub: create ns + pull-secret, apply acm-resources.yaml")
	fmt.Println("3. Download InfraEnv discovery ISO URL from hub")
	fmt.Printf("4. mini-mock cluster attach-iso --config <cfg> --iso ./discovery.iso\n")
	fmt.Println("5. Wait for Agents; approve / bind as masters; watch AgentClusterInstall")
	fmt.Printf("Nodes: ")
	for i, n := range nodes {
		if i > 0 {
			fmt.Print(", ")
		}
		fmt.Print(n.Name)
	}
	fmt.Println()
	if opts.Manual || opts.DryRun {
		fmt.Println("(dry-run/manual: VMs not actually started)")
	}
	_ = cfg
}

func or(a, b string) string {
	if a != "" {
		return a
	}
	return b
}
