apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-me
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: mock-me
    dasmlab.org/cluster: 2026-prod-1
spec:
  project: default
  source:
    repoURL: git@github.com:lmcdasm/dasmlab-live-cicd.git
    targetRevision: main
    path: clusters/2026-prod-1/mock-me/live
    directory:
      recurse: false
      include: mock-me-v*.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mock-me-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
