<template>
  <q-page padding>
    <div class="row items-center q-mb-md">
      <q-btn flat dense icon="arrow_back" :to="{ name: 'topology', params: { id } }" />
      <div class="text-h4 q-ml-sm">Wizard</div>
      <q-space />
      <q-btn outline color="primary" label="Topology" :to="{ name: 'topology', params: { id } }" class="q-mr-sm" />
      <q-btn color="primary" icon="save" label="Save gaps" :loading="saving" @click="persist" />
    </div>

    <div v-if="loading" class="row justify-center q-my-xl"><q-spinner size="3em" color="primary" /></div>
    <template v-else-if="mockup">
      <p class="text-body2 text-grey-8 q-mb-md">
        {{ mockup.metadata.name }} — capture parameters (including MVP gaps), derive YAML, then run CLI with
        <code>--manual</code> as needed.
      </p>

      <q-stepper v-model="step" color="primary" animated flat bordered header-nav>
        <q-step :name="1" title="Hub create" icon="dns" :done="step > 1">
          <div class="text-subtitle1 q-mb-sm">Local Agent-based ISO → SNO (OCP only, not ACM)</div>
          <q-markup-table flat bordered dense class="q-mb-md">
            <tbody>
              <tr><td>Hostname</td><td>{{ mockup.spec.hub.hostname }}</td></tr>
              <tr><td>Profile / size</td><td>{{ mockup.spec.hub.profile }} · {{ mockup.spec.hub.cpu }}c / {{ mockup.spec.hub.memoryMiB }}MiB / {{ mockup.spec.hub.diskGiB }}GiB</td></tr>
              <tr><td>Version</td><td>{{ mockup.spec.hub.version }}</td></tr>
              <tr><td>ISO</td><td>Generated by <code>openshift-install agent create image</code></td></tr>
            </tbody>
          </q-markup-table>
          <q-input v-model="mockup.spec.gaps.pullSecretFile" outlined dense label="Pull secret file path" class="q-mb-sm"
            hint="MVP gap — $PULL_SECRET_FILE" />
          <q-input v-model="mockup.spec.gaps.sshPublicKeyFile" outlined dense label="SSH public key path" class="q-mb-md"
            hint="MVP gap — $SSH_PUBLIC_KEY_FILE" />
          <q-banner class="bg-grey-2 q-mb-md" rounded dense>
            After derive:
            <code>mini-acm --manual hub create --config data/mockups/{{ id }}/out/hub.yaml --skip-wait --skip-acm</code>
          </q-banner>
          <q-stepper-navigation>
            <q-btn color="primary" label="Continue" @click="step = 2" />
          </q-stepper-navigation>
        </q-step>

        <q-step :name="2" title="Install ACM" icon="extension" :done="step > 2">
          <div class="text-subtitle1 q-mb-sm">Operators on the live hub — no second ISO</div>
          <q-toggle v-model="mockup.spec.hub.installACM" label="Install ACM after hub" class="q-mb-sm" />
          <q-input v-model="mockup.spec.acm.mceChannel" outlined dense label="MCE channel" class="q-mb-sm" />
          <q-input v-model="mockup.spec.acm.acmChannel" outlined dense label="ACM channel" class="q-mb-sm" />
          <q-input v-model="mockup.spec.gaps.hubKubeconfig" outlined dense label="Hub kubeconfig path" class="q-mb-md"
            :hint="`default: data/hub-${mockup.metadata.name}/auth/kubeconfig`" />
          <q-banner class="bg-grey-2 q-mb-md" rounded dense>
            <code>mini-acm hub install-acm --config data/mockups/{{ id }}/out/hub.yaml</code>
          </q-banner>
          <q-stepper-navigation>
            <q-btn flat label="Back" @click="step = 1" class="q-mr-sm" />
            <q-btn color="primary" label="Continue" @click="step = 3" />
          </q-stepper-navigation>
        </q-step>

        <q-step :name="3" title="Cluster create" icon="developer_board" :done="step > 3">
          <div class="text-subtitle1 q-mb-sm">
            3 VMs + DNS/HAProxy + CR YAML (ClusterDeployment / AgentClusterInstall / InfraEnv) — <strong>no ISO yet</strong>
          </div>
          <div v-for="c in mockup.spec.clusters" :key="c.id" class="q-mb-md">
            <q-card flat bordered>
              <q-card-section>
                <div class="text-subtitle2">{{ c.label }} ({{ c.name }})</div>
                <div class="text-caption">
                  {{ c.count }}× {{ c.cpu }}c / {{ c.memoryMiB }}MiB / {{ c.diskGiB }}GiB · {{ c.profile }}
                </div>
              </q-card-section>
            </q-card>
          </div>
          <q-input v-model="mockup.spec.gaps.clusterImageSet" outlined dense label="ClusterImageSet name" class="q-mb-md"
            hint="MVP gap — must match AgentClusterInstall imageSetRef (e.g. img418-x86-64-appsub)" />
          <q-banner class="bg-grey-2 q-mb-md" rounded dense>
            <code>mini-acm --manual cluster create --config data/mockups/{{ id }}/out/cluster-….yaml</code>
            then apply ns + pull-secret + acm-resources.yaml on hub.
          </q-banner>
          <q-stepper-navigation>
            <q-btn flat label="Back" @click="step = 2" class="q-mr-sm" />
            <q-btn color="primary" label="Continue" @click="step = 4" />
          </q-stepper-navigation>
        </q-step>

        <q-step :name="4" title="Attach ISO" icon="album">
          <div class="text-subtitle1 q-mb-sm">Boot discovery ISO → Agents → install</div>
          <q-input v-model="mockup.spec.gaps.discoveryISO" outlined dense label="Discovery ISO path" class="q-mb-sm"
            hint="MVP gap — download from InfraEnv status.isoDownloadURL" />
          <q-toggle v-model="mockup.spec.gaps.manualApprove" label="Manual Agent approve / bind" class="q-mb-md" />
          <q-banner class="bg-grey-2 q-mb-md" rounded dense>
            <code>mini-acm cluster attach-iso --config … --iso {{ mockup.spec.gaps.discoveryISO || './discovery.iso' }}</code>
          </q-banner>
          <q-stepper-navigation>
            <q-btn flat label="Back" @click="step = 3" class="q-mr-sm" />
            <q-btn color="primary" icon="description" label="Derive YAML" :loading="deriving" @click="onDerive" />
          </q-stepper-navigation>
        </q-step>
      </q-stepper>
    </template>
  </q-page>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { Notify } from 'quasar'
import { getMockup, saveMockup, deriveMockup } from 'src/services/api'

const props = defineProps({ id: { type: String, required: true } })

const mockup = ref(null)
const loading = ref(true)
const saving = ref(false)
const deriving = ref(false)
const step = ref(1)

async function load() {
  loading.value = true
  try {
    mockup.value = await getMockup(props.id)
    if (!mockup.value.spec.gaps) {
      mockup.value.spec.gaps = {
        pullSecretFile: '',
        sshPublicKeyFile: '',
        clusterImageSet: '',
        discoveryISO: '',
        hubKubeconfig: '',
        manualApprove: true,
      }
    }
  } catch (e) {
    Notify.create({ type: 'negative', message: e.message })
  } finally {
    loading.value = false
  }
}

async function persist() {
  saving.value = true
  try {
    mockup.value = await saveMockup(props.id, mockup.value)
    Notify.create({ type: 'positive', message: 'Saved.' })
  } catch (e) {
    Notify.create({ type: 'negative', message: e.response?.data || e.message })
  } finally {
    saving.value = false
  }
}

async function onDerive() {
  deriving.value = true
  try {
    await persist()
    const res = await deriveMockup(props.id)
    Notify.create({
      type: 'positive',
      message: `Derived YAML: ${Object.values(res.paths || {}).join(', ')}`,
      timeout: 6000,
    })
  } catch (e) {
    Notify.create({ type: 'negative', message: e.response?.data || e.message })
  } finally {
    deriving.value = false
  }
}

onMounted(load)
</script>
