package deploy

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func acmManifestBundle(mceChannel, acmChannel string) string {
	if strings.TrimSpace(mceChannel) == "" {
		mceChannel = "stable-2.7"
	}
	if strings.TrimSpace(acmChannel) == "" {
		acmChannel = "release-2.12"
	}
	return fmt.Sprintf(`# generated by mock-me deploy
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    mock-me.dasmlab.org/managed: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: multicluster-engine
  source: redhat-operators
  sourceNamespace: openshift-marketplace
`, mceChannel) + fmt.Sprintf(`---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
`, acmChannel)
}

// installACMOperators copies kubeconfig to the host and applies MCE+ACM via EE oc, waiting for CSVs.
func (e *Engine) installACMOperators(j *Job, remoteRoot, localKC, mceChannel, acmChannel string) error {
	kcBytes, err := os.ReadFile(localKC)
	if err != nil {
		return fmt.Errorf("read hub kubeconfig: %w", err)
	}
	remoteKC := remoteRoot + "/acm/kubeconfig"
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteKC, kcBytes); err != nil {
		return err
	}
	manifests := acmManifestBundle(mceChannel, acmChannel)
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/operators.yaml", []byte(manifests)); err != nil {
		return err
	}
	_ = e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/channels.txt", []byte(
		fmt.Sprintf("ACM channel=%s MCE=%s\n", acmChannel, mceChannel)))

	img := EEImage()
	e.log(j, StageACM, "apply MCE subscription via EE oc (channel=%s)", mceChannel)
	_ = e.SaveJob(j)

	// Phase 1: namespace + OG + MCE subscription only (MCE CR needs CRDs from CSV).
	phase1 := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
KC="$ROOT/acm/kubeconfig"
run_oc() {
  podman run --rm \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
run_oc apply -f - <<'YAML'
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: multicluster-engine
  source: redhat-operators
  sourceNamespace: openshift-marketplace
YAML
echo MCE_SUB_APPLIED=1
run_oc get sub -n open-cluster-management || true
`, remoteRoot, img, mceChannel)

	out, _, err := e.inv.RunScript(j.InventoryID, phase1)
	if err != nil {
		return fmt.Errorf("ACM MCE subscription: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCE sub apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "multicluster-engine", "mce"); err != nil {
		return err
	}

	phaseMCE := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
run_oc() {
  podman run --rm \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
run_oc apply -f - <<'YAML'
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec: {}
YAML
echo MCE_CR_APPLIED=1
`, remoteRoot, img)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseMCE)
	if err != nil {
		return fmt.Errorf("MultiClusterEngine apply: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCE CR:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	phaseACMSub := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
run_oc() {
  podman run --rm \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
run_oc apply -f - <<'YAML'
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
YAML
echo ACM_SUB_APPLIED=1
`, remoteRoot, img, acmChannel)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseACMSub)
	if err != nil {
		return fmt.Errorf("ACM subscription: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "ACM sub apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "advanced-cluster-management", "acm"); err != nil {
		return err
	}

	phaseMCH := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
run_oc() {
  podman run --rm \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
run_oc apply -f - <<'YAML'
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
YAML
echo MCH_APPLIED=1
run_oc get csv -n open-cluster-management || true
run_oc get mch -n open-cluster-management || true
`, remoteRoot, img)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseMCH)
	if err != nil {
		return fmt.Errorf("MultiClusterHub apply: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCH apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "advanced-cluster-management", "acm-final"); err != nil {
		return err
	}
	return nil
}

func (e *Engine) waitForCSV(j *Job, remoteRoot, nameContains, label string) error {
	deadline := time.Now().Add(acmWaitTimeout())
	img := EEImage()
	e.log(j, StageACM, "waiting up to %s for CSV matching %q (%s)", acmWaitTimeout(), nameContains, label)
	_ = e.SaveJob(j)
	var last string
	for attempt := 1; time.Now().Before(deadline); attempt++ {
		script := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
NEED=%q
run_oc() {
  podman run --rm \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
echo "CSV_POLL=%d need=$NEED"
set +e
OUT=$(run_oc get csv -n open-cluster-management -o jsonpath='{range .items[*]}{.metadata.name}{"="}{.status.phase}{"\n"}{end}' 2>&1)
RC=$?
set -e
echo "$OUT"
if [ "$RC" -eq 0 ]; then
  echo "$OUT" | grep -i "$NEED" | grep -qiE '=Succeeded|=Available' && echo CSV_OK=1 || true
fi
`, remoteRoot, img, nameContains, attempt)
		out, _, err := e.inv.RunScript(j.InventoryID, script)
		if err != nil {
			last = truncate(out, 600)
			e.log(j, StageACM, "CSV poll #%d error: %v (%s)", attempt, err, last)
		} else {
			last = trimHostOut(out)
			e.log(j, StageACM, "CSV poll #%d:\n%s", attempt, last)
			_ = e.SaveJob(j)
			if strings.Contains(out, "CSV_OK=1") {
				return nil
			}
		}
		remain := time.Until(deadline).Round(time.Second)
		if remain <= 0 {
			break
		}
		sleep := 60 * time.Second
		if remain < sleep {
			sleep = remain
		}
		time.Sleep(sleep)
	}
	return fmt.Errorf("ACM timed out after %s waiting for CSV %q Available/Succeeded (last: %s)", acmWaitTimeout(), nameContains, last)
}
