package deploy

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func acmManifestBundle(mceChannel, acmChannel string) string {
	if strings.TrimSpace(mceChannel) == "" {
		mceChannel = "stable-2.7"
	}
	if strings.TrimSpace(acmChannel) == "" {
		acmChannel = "release-2.12"
	}
	return fmt.Sprintf(`# generated by mock-me deploy
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    mock-me.dasmlab.org/managed: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: multicluster-engine
  source: redhat-operators
  sourceNamespace: openshift-marketplace
`, mceChannel) + fmt.Sprintf(`---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
`, acmChannel)
}

func ocRunnerSnippet(hubIP string) string {
	if strings.TrimSpace(hubIP) == "" {
		hubIP = "10.77.30.20"
	}
	// Avoid fmt verbs inside the shell snippet (fragile with nested % quoting).
	return strings.ReplaceAll(`run_oc() {
  # Always apply from files (podman needs -i for stdin; heredocs are fragile over SSH).
  podman run --rm \
    --add-host "api.lab-e2e.lab.example.net:__HUB_IP__" \
    --add-host "api-int.lab-e2e.lab.example.net:__HUB_IP__" \
    --dns 10.77.30.1 \
    -v "$ROOT/acm:/acm:Z" \
    -e KUBECONFIG=/acm/kubeconfig \
    --entrypoint /usr/local/bin/oc \
    "$EE_IMAGE" "$@"
}
prep_kc() {
  # Disposable kubeconfig: hub IP + insecure (asset CA hostname often mismatches).
  cp -a "$ROOT/acm/kubeconfig.src" "$ROOT/acm/kubeconfig"
  sed -i -e "s|https://api\\.[^:]*:6443|https://__HUB_IP__:6443|" "$ROOT/acm/kubeconfig" || true
  if ! grep -q 'insecure-skip-tls-verify' "$ROOT/acm/kubeconfig"; then
    sed -i -e "s|server: https://__HUB_IP__:6443|insecure-skip-tls-verify: true\\n    server: https://__HUB_IP__:6443|" "$ROOT/acm/kubeconfig" || true
  fi
  grep -v 'certificate-authority' "$ROOT/acm/kubeconfig" > "$ROOT/acm/kubeconfig.tmp" 2>/dev/null \
    && mv "$ROOT/acm/kubeconfig.tmp" "$ROOT/acm/kubeconfig" || true
}
`, "__HUB_IP__", hubIP)
}

// installACMOperators copies kubeconfig to the host and applies MCE+ACM via EE oc, waiting for CSVs.
func (e *Engine) installACMOperators(j *Job, remoteRoot, localKC, mceChannel, acmChannel string) error {
	kcBytes, err := os.ReadFile(localKC)
	if err != nil {
		return fmt.Errorf("read hub kubeconfig: %w", err)
	}
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/kubeconfig.src", kcBytes); err != nil {
		return err
	}
	manifests := acmManifestBundle(mceChannel, acmChannel)
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/operators.yaml", []byte(manifests)); err != nil {
		return err
	}
	_ = e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/channels.txt", []byte(
		fmt.Sprintf("ACM channel=%s MCE=%s\n", acmChannel, mceChannel)))

	hubIP := "10.77.30.20"
	img := EEImage()
	runner := ocRunnerSnippet(hubIP)

	// Wait for cluster to be usable before OLMs (API_OK alone is too early).
	e.log(j, StageACM, "waiting for clusterversion Available before ACM operators")
	_ = e.SaveJob(j)
	waitCV := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
%s
prep_kc
DEADLINE=$(( $(date +%%s) + 3600 ))
while [ $(date +%%s) -lt $DEADLINE ]; do
  set +e
  OUT=$(run_oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Available")].status}{"|"}{.status.conditions[?(@.type=="Progressing")].status}{"|"}{.status.desired.version}' 2>&1)
  RC=$?
  set -e
  echo "CV=$OUT"
  if [ "$RC" -eq 0 ] && echo "$OUT" | grep -q '^True|'; then
    echo CLUSTER_AVAILABLE=1
    exit 0
  fi
  sleep 30
done
echo CLUSTER_AVAILABLE=0
exit 1
`, remoteRoot, img, runner)
	out, _, err := e.inv.RunScript(j.InventoryID, waitCV)
	if err != nil {
		return fmt.Errorf("wait clusterversion Available: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "cluster ready:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	e.log(j, StageACM, "apply MCE subscription via EE oc (channel=%s)", mceChannel)
	_ = e.SaveJob(j)

	phase1YAML := fmt.Sprintf(`apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: multicluster-engine
  source: redhat-operators
  sourceNamespace: openshift-marketplace
`, mceChannel)
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/phase1-mce-sub.yaml", []byte(phase1YAML)); err != nil {
		return err
	}

	phase1 := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
%s
prep_kc
run_oc apply -f /acm/phase1-mce-sub.yaml
echo MCE_SUB_APPLIED=1
run_oc get sub -n open-cluster-management || true
`, remoteRoot, img, runner)

	out, _, err = e.inv.RunScript(j.InventoryID, phase1)
	if err != nil {
		return fmt.Errorf("ACM MCE subscription: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCE sub apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "multicluster-engine", "mce"); err != nil {
		return err
	}

	mceCR := `apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec: {}
`
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/phase-mce-cr.yaml", []byte(mceCR)); err != nil {
		return err
	}
	phaseMCE := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
%s
prep_kc
run_oc apply -f /acm/phase-mce-cr.yaml
echo MCE_CR_APPLIED=1
`, remoteRoot, img, runner)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseMCE)
	if err != nil {
		return fmt.Errorf("MultiClusterEngine apply: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCE CR:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	acmSub := fmt.Sprintf(`apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: %s
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
`, acmChannel)
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/phase-acm-sub.yaml", []byte(acmSub)); err != nil {
		return err
	}
	phaseACMSub := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
%s
prep_kc
run_oc apply -f /acm/phase-acm-sub.yaml
echo ACM_SUB_APPLIED=1
`, remoteRoot, img, runner)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseACMSub)
	if err != nil {
		return fmt.Errorf("ACM subscription: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "ACM sub apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "advanced-cluster-management", "acm"); err != nil {
		return err
	}

	mch := `apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
`
	if err := e.inv.WriteRemoteFile(j.InventoryID, remoteRoot+"/acm/phase-mch.yaml", []byte(mch)); err != nil {
		return err
	}
	phaseMCH := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
%s
prep_kc
run_oc apply -f /acm/phase-mch.yaml
echo MCH_APPLIED=1
run_oc get csv -n open-cluster-management || true
run_oc get mch -n open-cluster-management || true
`, remoteRoot, img, runner)
	out, _, err = e.inv.RunScript(j.InventoryID, phaseMCH)
	if err != nil {
		return fmt.Errorf("MultiClusterHub apply: %v (%s)", err, truncate(out, 800))
	}
	e.log(j, StageACM, "MCH apply:\n%s", trimHostOut(out))
	_ = e.SaveJob(j)

	if err := e.waitForCSV(j, remoteRoot, "advanced-cluster-management", "acm-final"); err != nil {
		return err
	}
	return nil
}

func (e *Engine) waitForCSV(j *Job, remoteRoot, nameContains, label string) error {
	deadline := time.Now().Add(acmWaitTimeout())
	img := EEImage()
	hubIP := "10.77.30.20"
	runner := ocRunnerSnippet(hubIP)
	e.log(j, StageACM, "waiting up to %s for CSV matching %q (%s)", acmWaitTimeout(), nameContains, label)
	_ = e.SaveJob(j)
	var last string
	for attempt := 1; time.Now().Before(deadline); attempt++ {
		script := fmt.Sprintf(`set -eu
ROOT=%q
EE_IMAGE=%q
NEED=%q
%s
prep_kc
echo "CSV_POLL=%d need=$NEED"
set +e
OUT=$(run_oc get csv -n open-cluster-management -o jsonpath='{range .items[*]}{.metadata.name}{"="}{.status.phase}{"\n"}{end}' 2>&1)
RC=$?
set -e
echo "$OUT"
if [ "$RC" -eq 0 ]; then
  echo "$OUT" | grep -i "$NEED" | grep -qiE '=Succeeded|=Available' && echo CSV_OK=1 || true
fi
`, remoteRoot, img, nameContains, runner, attempt)
		out, _, err := e.inv.RunScript(j.InventoryID, script)
		if err != nil {
			last = truncate(out, 600)
			e.log(j, StageACM, "CSV poll #%d error: %v (%s)", attempt, err, last)
		} else {
			last = trimHostOut(out)
			e.log(j, StageACM, "CSV poll #%d:\n%s", attempt, last)
			_ = e.SaveJob(j)
			if strings.Contains(out, "CSV_OK=1") {
				return nil
			}
		}
		remain := time.Until(deadline).Round(time.Second)
		if remain <= 0 {
			break
		}
		sleep := 60 * time.Second
		if remain < sleep {
			sleep = remain
		}
		time.Sleep(sleep)
	}
	return fmt.Errorf("CSV %q not Available/Succeeded after %s (last: %s)", nameContains, acmWaitTimeout(), last)
}
